language: java
java:
  - 1.6
  - 1.7
  - 1.8
sudo: required
env:
  global:
  - GH_PROJECT_NAME: cp-parser
  - GIT_AUTHOR_NAME: TravisCI
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`
  - GRADLE_USER_HOME=`pwd`/.gradle

before_script:
    - chmod +x gradlew
script:
 - gradle buildPlugin
 - echo "Post Build"
 - cd $CI_HOME/build/distributions && pwd && ls -la
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  file: $CI_HOME/build/distributions/*.zip